# Generated by Django 5.0.6 on 2024-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('publication_date', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('image_urls', models.JSONField()),
                ('entities', models.JSONField()),
            ],
        ),
    ]
